### ISSUE TITLE
Debugging in Xcode works only on "My Mac" device

### ISSUE THREAD

**Issue by piobyz** [americanexpress/xcprojectlint#1]
Hi, I've just started discovering this project, and I've noticed that for "Debugging in Xcode" to work I need to select "My Mac" as a device to run tests on, not sure if this is by design.

For e.g. iPhone simulator it returns 2 errors in Process.swift:
- Process.swift:240:26: Cannot invoke initializer for type 'posix_spawnattr_t' with no arguments
- Process.swift:284:27: Cannot invoke initializer for type 'posix_spawn_file_actions_t' with no arguments

Thanks!

**Comment by kalkwarf** [comment]
Thanks for your interest.

`xcprojectlint` is a developer tool, meant to run on your development machine. Since there are no Xcode projects on an iOS device, trying to run the code there wouldn't make sense.
