### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by piobyz** [americanexpress/xcprojectlint#2]
Hi,

I try to lint some projects, but both mine and generated xcprojectlint.xcodeproj returns only: "Illegal instruction: 4".

What I've tried to run:
$ ./xcprojectlint --report error --validations build-settings-externalized --project /Users/piotr/Projects/Github/xcprojectlint/xcprojectlint.xcodeproj

and all other validations, including *all*.

What am I doing wrong? All tests pass successfully, both from CLI and Xcode.

**Comment by kalkwarf** [comment]
Interesting.

The project file built by SPM is missing some data I was expecting (specifically, the `productReference` key in `NativeTarget`). I'll fix that shortly.

I can't say what's happening with your project. If it's another SPM-generated project, it's likely the same problem. If it's your own project, you can try running `xcprojectlint` from Xcode, and see where the error is occurring.

Set your arguments like these (specifying the full path to your project file), and run.

![image](https://user-images.githubusercontent.com/1033839/40724141-58d00482-63ee-11e8-87d5-98f5a090ec35.png)
