### ISSUE TITLE
Outputs error concerning not finding expected key (fileRef)

### ISSUE THREAD

**Issue by lordcodes** [americanexpress/xcprojectlint#7]
xcprojectlint is being ran as a build phase on an iOS Xcode project.

It outputs:

We didn't find an expected key (fileRef) in "(type(of: self))". Please open a bug report at https://github.com/americanexpress/xcprojectlint/issues so we can investigate.

**Comment by RomainBoulay** [comment]
Hey American Express!

Same problem here. My team used to have a clean output and we got this message recently. @HeEAaD, @kalkwarf any idea what could cause this? 

Thanks!

**Comment by kalkwarf** [comment]
@RomainBoulay The short answer is, an assumption I made about the project file structure is no longer correct for your project file.

Can you share the project file with me? (I don't need the rest of the source/supporting files)

**Comment by orj** [comment]
@lordcodes I fixed the error message recently so that it gives more correct info.

**Comment by lordcodes** [comment]
@orj Thank you very much, I will take a look.
